### ISSUE TITLE
vagrantでWordPressを構築する

### ISSUE THREAD

**Issue by RVIRUS0817** [haruka002/My-awesome-project#1]
## 要件

- macにvagrantをインストールしてCentOS7の最新がダウンロードできる状態にすること
https://qiita.com/sudachi808/items/3614fd90f9025973de4b

- wordpressを動作させる
  - mentaユーザー作成
  - mentaユーザーでのssh鍵認証
  - nginxのインストール
  - php-fpmのインストール(sockets通信)
  - MySQL5.7のインストール(wordpress DB作成とそれに伴うユーザー権限の設定)
  - 192.168.33.10でアクセスしてほしいが、menta.meでアクセスできるようにしてほしい
  - https(オレオレ証明書)でアクセスできるように
  - http→httpsにリダイレクト設定をいれる
  - MySQLのバックアップシェルスクリプトの作成(第５世代)

上記設定ができたら連絡をお願いします🙇🏼‍♂️

## 参考
https://qiita.com/klab2/items/2c3137a291991387da03

##  補足
apacheでもwebサーバーを動かしてほしいので、
apacheとnginxのメリットデメリットを理解できているのか自分なりに調べてみてください。

**Comment by haruka002** [comment]
pwd [ ~/MyVagrant/MyCentOS ]
command [ vagrant box add study-server https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.2/vagrant-centos-7.2.box ]

log [
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'study-server' (v0) for provider:
    box: Downloading: https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.2/vagrant-centos-7.2.box
    box: Download redirected to host: github-production-release-asset-2e65be.s3.amazonaws.com
    box: Progress: 0% (Rate: 1306k/s, Estimated time remaining    box: Progress: 0% (Rate: 1529k/s, Estimated time remaining    box: Progress: 1% (Rate: 2254k/s, Estimated time remaining    box: Progress: 6% (Rate: 6788k/s, Estimated time remaining    box: Progress: 7% (Rate: 6102k/s, Estimated time remaining    box: Progress: 10% (Rate: 4839k/s, Estimated time remainin    box: Progress: 11% (Rate: 4973k/s, Estimated time remainin    box: Progress: 12% (Rate: 5092k/s, Estimated time remainin    box: Progress: 15% (Rate: 5256k/s, Estimated time remainin    box: Progress: 17% (Rate: 5337k/s, Estimated time remainin    box: Progress: 21% (Rate: 6547k/s, Estimated time remainin    box: Progress: 24% (Rate: 7683k/s, Estimated time remainin    box: Progress: 31% (Rate: 10.6M/s, Estimated time remainin    box: Progress: 35% (Rate: 11.1M/s, Estimated time remainin    box: Progress: 42% (Rate: 10.3M/s, Estimated time remainin    box: Progress: 46% (Rate: 9922k/s, Estimated time remainin    box: Progress: 50% (Rate: 8924k/s, Estimated time remainin    box: Progress: 59% (Rate: 9088k/s, Estimated time remainin    box: Progress: 67% (Rate: 7968k/s, Estimated time remainin    box: Progress: 77% (Rate: 8591k/s, Estimated time remainin    box: Progress: 100% (Rate: 9568k/s, Estimated time remaini    box:
==> box: Successfully added box 'study-server' (v0) for 'virtualbox'!
]
command [ vagrant init study-server ]

log [
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
]

command [ vagrant up ]
log [
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'study-server'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: MyCentOS_default_1581516184223_31623
Vagrant is currently configured to create VirtualBox synced folders with
the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
guest is not trusted, you may want to disable this option. For more
information on this option, please refer to the VirtualBox manual:

  https://www.virtualbox.org/manual/ch04.html#sharedfolders

This option can be disabled globally with an environment variable:

  VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

or on a per folder basis within the Vagrantfile:

  config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.30
    default: VirtualBox Version: 6.1
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/harub/MyVagrant/MyCentOS
]

**Comment by haruka002** [comment]
## Markdown記法について

- 以下参照先
https://qiita.com/tbpgr/items/989c6badefff69377da7
